
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class Praktik_7 extends javax.swing.JFrame {

    String temp="";
    Double ti, bt,h1;
    /**
     * Creates new form Praktik_7
     */
    public Praktik_7() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bKeluar = new javax.swing.JButton();
        bHitung = new javax.swing.JButton();
        bCoba = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfHsl2 = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        tfTinggi = new javax.swing.JTextField();
        tfIdeal = new javax.swing.JTextField();
        tfHsl1 = new javax.swing.JTextField();
        tfBerat = new javax.swing.JTextField();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Poiret One", 3, 18)); // NOI18N
        jLabel1.setText("CEK TUBUH IDEAL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 10, 170, 22);

        jLabel2.setFont(new java.awt.Font("Poiret One", 3, 18)); // NOI18N
        jLabel2.setText("Jenis Kelamin");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 140, 180, 22);

        jLabel3.setFont(new java.awt.Font("Poiret One", 3, 18)); // NOI18N
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 50, 80, 22);

        jLabel4.setFont(new java.awt.Font("Poiret One", 3, 18)); // NOI18N
        jLabel4.setText("Tinggi badan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 80, 160, 22);

        jLabel5.setFont(new java.awt.Font("Poiret One", 3, 18)); // NOI18N
        jLabel5.setText("Berat badan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 110, 160, 22);

        bKeluar.setBackground(new java.awt.Color(153, 153, 255));
        bKeluar.setFont(new java.awt.Font("Poiret One", 3, 18)); // NOI18N
        bKeluar.setText("Keluar");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(bKeluar);
        bKeluar.setBounds(320, 170, 130, 40);

        bHitung.setBackground(new java.awt.Color(153, 153, 255));
        bHitung.setFont(new java.awt.Font("Poiret One", 3, 18)); // NOI18N
        bHitung.setText("Hitung");
        bHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHitungActionPerformed(evt);
            }
        });
        getContentPane().add(bHitung);
        bHitung.setBounds(30, 170, 110, 40);

        bCoba.setBackground(new java.awt.Color(153, 153, 255));
        bCoba.setFont(new java.awt.Font("Poiret One", 3, 18)); // NOI18N
        bCoba.setText("Coba Lagi");
        bCoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCobaActionPerformed(evt);
            }
        });
        getContentPane().add(bCoba);
        bCoba.setBounds(160, 170, 140, 40);

        jLabel6.setFont(new java.awt.Font("Poiret One", 3, 18)); // NOI18N
        jLabel6.setText("Hasil Diagnosa Kesehatan Anda :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 270, 330, 30);

        jLabel7.setFont(new java.awt.Font("Poiret One", 3, 18)); // NOI18N
        jLabel7.setText("Berat badan ideal anda adalah");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 230, 310, 30);
        getContentPane().add(tfHsl2);
        tfHsl2.setBounds(20, 350, 460, 30);

        tfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaActionPerformed(evt);
            }
        });
        getContentPane().add(tfNama);
        tfNama.setBounds(190, 40, 150, 30);

        tfTinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTinggiActionPerformed(evt);
            }
        });
        getContentPane().add(tfTinggi);
        tfTinggi.setBounds(190, 70, 40, 30);

        tfIdeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdealActionPerformed(evt);
            }
        });
        getContentPane().add(tfIdeal);
        tfIdeal.setBounds(350, 230, 70, 30);
        getContentPane().add(tfHsl1);
        tfHsl1.setBounds(20, 310, 460, 30);
        getContentPane().add(tfBerat);
        tfBerat.setBounds(190, 100, 40, 30);

        rbLaki.setFont(new java.awt.Font("Poiret One", 3, 18)); // NOI18N
        rbLaki.setText("Laki-laki");
        getContentPane().add(rbLaki);
        rbLaki.setBounds(340, 130, 130, 31);

        rbPerempuan.setFont(new java.awt.Font("Poiret One", 3, 18)); // NOI18N
        rbPerempuan.setText("Perempuan");
        getContentPane().add(rbPerempuan);
        rbPerempuan.setBounds(190, 130, 140, 31);

        setBounds(0, 0, 509, 442);
    }// </editor-fold>//GEN-END:initComponents

    private void tfTinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTinggiActionPerformed

    private void tfNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaActionPerformed

    private void bHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHitungActionPerformed
        // TODO add your handling code here:
        if(tfBerat.getText().equals("")||tfTinggi.getText().equals("")||tfNama.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Kotak isian belum diisi");}
        else if(rbLaki.isSelected()||rbPerempuan.isSelected()){
        try{
        Proses();
        }
        catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Inputan ada yang salah");
                }
        }
        else{
            JOptionPane.showMessageDialog(null, "Jenis Kelamin belum diisi");
        }
    }//GEN-LAST:event_bHitungActionPerformed

    private void bCobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCobaActionPerformed
        // TODO add your handling code here:
        tfNama.setText("");
        tfBerat.setText("");
        tfTinggi.setText("");
        tfIdeal.setText("");
        tfHsl1.setText("");
        tfHsl2.setText("");
        rbLaki.setSelected(false);
        rbPerempuan.setSelected(false);
    }//GEN-LAST:event_bCobaActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bKeluarActionPerformed

    private void tfIdealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdealActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Praktik_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Praktik_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Praktik_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Praktik_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Praktik_7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCoba;
    private javax.swing.JButton bHitung;
    private javax.swing.JButton bKeluar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTextField tfBerat;
    private javax.swing.JTextField tfHsl1;
    private javax.swing.JTextField tfHsl2;
    private javax.swing.JTextField tfIdeal;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfTinggi;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
    ti=Double.valueOf(tfTinggi.getText());
    bt=Double.valueOf(tfBerat.getText());
    
    if(rbPerempuan.isSelected()){
        h1=(ti-110)*1;
    }
    else if(rbLaki.isSelected()){
        h1=(ti-114)*1;
    }
    temp=Double.toString(h1.intValue());
    
    if(h1<bt){
        tfIdeal.setText(temp);
        tfHsl1.setText("Maaf "+tfNama.getText()+" , sepertinya Anda Overweigtht");
        tfHsl2.setText("Banyak olahraga ya, hindari juga makanan berkolesterol serta makanan berkalori");
    }
    else if(h1>bt){
        tfIdeal.setText(temp);
        tfHsl1.setText("Maaf "+tfNama.getText()+" , sepertinya Anda underweight");
        tfHsl2.setText("Banyak konsumsi karbohidrat ya");
    }
    else{
        tfIdeal.setText(temp);
        tfHsl1.setText("Hai, "+tfNama.getText()+"! Berat badan Anda sudah ideal");
        tfHsl2.setText("Tetap dengan pola hidup sehat Anda");
    }
    }
    }
